################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
 
    # SampleOrg defines an MSP using the sampleconfig.  It should never be used
    # in production but may be used as a template for other definitions
    - &OrdererOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: OrdererOrg
 
        # ID to load the MSP definition as
        ID: OrdererMSP
 
        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: crypto-config/ordererOrganizations/sc.com/msp
 
        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"
 
    - &Bosch
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: BoschMSP
 
        # ID to load the MSP definition as
        ID: BoschMSP
 
        MSPDir: crypto-config/peerOrganizations/bosch.sc.com/msp
 
        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('BoschMSP.admin', 'BoschMSP.peer', 'BoschMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('BoschMSP.admin', 'BoschMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('BoschMSP.admin')"
 
        # leave this flag set to true.
        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.bosch.sc.com
              Port: 7051
              
    - &FedEx
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: FedExMSP
 
        # ID to load the MSP definition as
        ID: FedExMSP
 
        MSPDir: crypto-config/peerOrganizations/fedex.sc.com/msp
 
        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('FedExMSP.admin', 'FedExMSP.peer', 'FedExMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('FedExMSP.admin', 'FedExMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('FedExMSP.admin')"
 
        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.fedex.sc.com
              Port: 9051
 
 
    - &Walmart
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: WalmartMSP
 
        # ID to load the MSP definition as
        ID: WalmartMSP
 
        MSPDir: crypto-config/peerOrganizations/walmart.sc.com/msp
 
        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('WalmartMSP.admin', 'WalmartMSP.peer', 'WalmartMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('WalmartMSP.admin', 'WalmartMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('WalmartMSP.admin')"
 
        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.walmart.sc.com
              Port: 11051
 
    

